#!/bin/bash

set -e

if [ $# -gt 0 ]; then
	if [[ $# != 1 || ! "$1" =~ ^[0-9]+$ ]]; then
		echo "Expect exactly one argument: number of additional kernels to keep"
		exit 1
	fi
	NUM_KERNELS_TO_KEEP=$1
else
	eval $(egrep '^[A-Z_]+=[0-9A-Z]+\s*$' /etc/rolling.conf -s)
fi

kernel_packages=()
skip=$NUM_KERNELS_TO_KEEP
current_kernel=linux-rolling_$(uname -r | sed 's/-ARCH//g; s/[.-]/_/g;')
# record all installed kernel versions except currently running to array
for p in $(pacman -Qtq | egrep 'linux-rolling_[1-9]' | grep -v  sort -n); do
	if [ "$p" = "$current_kernel" ]; then
		# current kernel version is also counted as skipped
		# this logic makes it impossible to simply `sort -rn | tail -n +$skip`
		# because if currently running version is in resulting list
		# we have to drop it and add one from filtered out versions
		if [ $skip -gt 0 ]; then
			skip=$(($skip - 1))
		fi
		continue
	fi
	kernel_packages[${#kernel_packages[@]}]=$p
done

num_packages_to_remove=$((${#kernel_packages[@]} - $skip))
if [ $num_packages_to_remove -lt 1 ]; then
	exit 0
fi

to_remove_kernel_packages=${kernel_packages[@]:0:$num_packages_to_remove}
SUDO=$(command -v sudo)
$SUDO pacman -R $to_remove_kernel_packages
