#!/bin/bash

while read -r line; do
	kernel_version=${line%-ARCH/version}
	kernel_version=${kernel_version##*-}
	installed=$(pacman -Qqs linux-rolling_${kernel_version//./_} | pacsort | head -n 1)
	if [ ! "$installed" ]; then
		continue
	fi

	package_version=${installed##linux-rolling_}
	package_release=${package_version##*_}
	package_version=${package_version%_*}
	package_version=${package_version//_/.}
	f="/usr/lib/modules/extramodules-$kernel_version-ARCH/version-$package_version-$package_release"
	if [ ! -e "$f" ]; then
		echo "Can't find $f. It must belong to $installed"
		continue
	fi
	ln -sf "$f" /usr/lib/modules/extramodules-$kernel_version-ARCH/version
done
